[package]
name = "appa"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
anyhow = "1.0.70"
async-trait = "0.1.68"
backoff = "0.4.0"
blake3 = "1.3.3"
chrono = "0.4.24"
cid = "0.10.1"
ignore = "0.4.20"
libipld = "0.16.0"
tokio = { version = "1.27.0", features = ["full"] }
wnfs = "0.1.20"

[dev-dependencies]
tempfile = "3.5.0"
